import gradient from '../images/level0gradient.jpeg';
import desertBackground from '../images/desert_background.jpg';
import mountainBackground from '../images/mountain_background.jpg';

const levels = [

    {
        level: 0,
        start: [20, 20],
        target: { x1: 10, y1: -6, x2: 10, y2: -9, x3: 6, y3: -9 },
        moves: [
            { id: 1, name: "(5, -3)", category: "preStage", moveType: "translate", ixt: 5, iyt: -3, style: "translate" },
            { id: 2, name: "Reflect X", category: "preStage", moveType: "reflect", reflectX: 1, reflectY: 0, cre: 0, style: "reflect-y" },
            { id: 3, name: "Reflect X", category: "preStage", moveType: "reflect", reflectX: 1, reflectY: 0, cre: 0, style: "reflect-y" },
            { id: 4, name: "Reflect X", category: "preStage", moveType: "reflect", reflectX: 1, reflectY: 0, cre: 0, style: "reflect-y" },
            { id: 5, name: "(5, -5)", category: "preStage", moveType: "translate", ixt: 5, iyt: -5, style: "translate" },
            { id: 6, name: "180°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: 180, style: "rotate-counter" },
            { id: 7, name: "Reflect Y", category: "preStage", moveType: "reflect", reflectX: 0, reflectY: 1, cre: 0, style: "reflect-x" },
            { id: 8, name: "Reflect Y", category: "preStage", moveType: "reflect", reflectX: 0, reflectY: 1, cre: 0, style: "reflect-x" },
            { id: 9, name: "90°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: -90, style: "rotate-clock" },
            { id: 10, name: "(0, -9)", category: "preStage", moveType: "translate", ixt: 0, iyt: -9, style: "translate" },
            { id: 11, name: "(0, -7)", category: "preStage", moveType: "translate", ixt: 0, iyt: -7, style: "translate" },
            { id: 12, name: "(-5, 3)", category: "preStage", moveType: "translate", ixt: -5, iyt: 3, style: "translate" },
            { id: 13, name: "270°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: -270, style: "rotate-clock" },
            { id: 14, name: "180°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: -180, style: "rotate-clock" },
            { id: 15, name: "90°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: 90, style: "rotate-counter" },
            { id: 16, name: "270°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: 270, style: "rotate-counter" },
            { id: 17, name: "(5, 0)", category: "preStage", moveType: "translate", ixt: 5, iyt: 0, style: "translate" },
            { id: 18, name: "(7, -2)", category: "preStage", moveType: "translate", ixt: 7, iyt: -2, style: "translate" },
            { id: 19, name: "(10, 0)", category: "preStage", moveType: "translate", ixt: 10, iyt: 0, style: "translate" },
            { id: 20, name: "(15, -15)", category: "preStage", moveType: "translate", ixt: 15, iyt: -15, style: "translate" },
            { id: 21, name: "(7, -3)", category: "preStage", moveType: "translate", ixt: 7, iyt: -3, style: "translate" },
            { id: 22, name: "(14, -6)", category: "preStage", moveType: "translate", ixt: 14, iyt: -6, style: "translate" },
            { id: 23, name: "(14, -9)", category: "preStage", moveType: "translate", ixt: 14, iyt: -9, style: "translate" },
            { id: 24, name: "(14, -16)", category: "preStage", moveType: "translate", ixt: 14, iyt: -16, style: "translate" },
            { id: 25, name: "(11, 0)", category: "preStage", moveType: "translate", ixt: 11, iyt: 0, style: "translate" },
            { id: 26, name: "(12, 0)", category: "preStage", moveType: "translate", ixt: 12, iyt: 0, style: "translate" },
            { id: 27, name: "(16, 0)", category: "preStage", moveType: "translate", ixt: 16, iyt: 0, style: "translate" },
            { id: 28, name: "(1, 0)", category: "preStage", moveType: "translate", ixt: 1, iyt: 0, style: "translate" },
            { id: 29, name: "(2, 0)", category: "preStage", moveType: "translate", ixt: 2, iyt: 0, style: "translate" },
            { id: 30, name: "(3, 0)", category: "preStage", moveType: "translate", ixt: 3, iyt: 0, style: "translate" },
            { id: 31, name: "(4, 0)", category: "preStage", moveType: "translate", ixt: 4, iyt: 0, style: "translate" },
            { id: 32, name: "(0, -6)", category: "preStage", moveType: "translate", ixt: 0, iyt: -6, style: "translate" },
            { id: 33, name: "(0, -13)", category: "preStage", moveType: "translate", ixt: 0, iyt: -13, style: "translate" },
            { id: 34, name: "(0, -18)", category: "preStage", moveType: "translate", ixt: 0, iyt: -18, style: "translate" },
        ],
        obstacles: [],
        popUpMessages: ["You Win!", "You Ran Out of Moves!", "Out of Bounds!"],
        theme: {
            backgroundImage: gradient,
            topContainerBackground: "#ffffff44",
            botContainerBackground: "#592e9940",
            menuContainerBackground: "",
            font: {type: "Courier", color: "#201207"},
            moveColour: {translate: "#ff9361", rotate: "#c561ff", reflect: "#ffbb61", text: "#201207"},
            grid: { axis: 0x808080, border: 0x000000, text: 0x000000 },
            playerLine: { color: 0xDAA520, weight: 5 },
            playerFill: { color: 0xFFD700, opacity: 1 },
            exitLine: { weight: 6, color: 0x000000 },
            exitFill: { color: 0x000000, opacity: 0.5 },
        },
    },
    {
        level: 1,
        start: [60, 100],
        target: { x1: 10, y1: -6, x2: 10, y2: -9, x3: 6, y3: -9 },
        moves: [
            { id: 1, name: "(5, -3)", category: "preStage", moveType: "translate", ixt: 5, iyt: -3, style: "translate" },
            { id: 2, name: "(5, -5)", category: "preStage", moveType: "translate", ixt: 5, iyt: -5, style: "translate" },
            { id: 3, name: "180°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: 180, style: "rotate-counter" },
            { id: 4, name: "90°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: -90, style: "rotate-clock" },
            { id: 5, name: "(0, -9)", category: "preStage", moveType: "translate", ixt: 0, iyt: -9, style: "translate" },
            { id: 6, name: "(-5, 3)", category: "preStage", moveType: "translate", ixt: -5, iyt: 3, style: "translate" },
            { id: 7, name: "(1, -5)", category: "preStage", moveType: "translate", ixt: 1, iyt: -5, style: "translate" },
            { id: 8, name: "Reflect X", category: "preStage", moveType: "reflect", reflectX: 1, reflectY: 0, cre: 0, style: "reflect-y" },
        ],
        obstacles: [],
        popUpMessages: ["You Wrangled Yerself a 'Right Triangle'!", "Yer Outta Moves, Partner!", "That There's Outta Bounds!"],
        theme: {
            backgroundImage: desertBackground,
            topContainerBackground: "#ffffff44",
            botContainerBackground: "#995e2e44",
            menuContainerBackground: "",
            font: {type: "Courier", color: "#201207"},
            moveColour: {translate: "#e28822", rotate: "#e25822", reflect: "#df9f71", text: "#201207"},
            grid: { axis: 0xFF0000, border: 0x000000, text: 0x000000 },
            playerLine: { color: 0xDAA520, weight: 5 },
            playerFill: { color: 0xFFD700, opacity: 1 },
            exitLine: { weight: 6, color: 0x000000 },
            exitFill: { color: 0x000000, opacity: 0.5 },
        },
    },
    {
        level: 2,
        start: [500, 620],
        target: { x1: -5, y1: 3, x2: -8, y2: 3, x3: -8, y3: 7 },
        moves: [
            { id: 1, name: "(5, -3)", category: "preStage", moveType: "translate", ixt: 5, iyt: -3, style: "translate" },
            { id: 2, name: "Reflect Y", category: "preStage", moveType: "reflect", reflectX: 0, reflectY: 1, cre: 0, style: "reflect-x" },
            { id: 3, name: "Reflect X", category: "preStage", moveType: "reflect", reflectX: 1, reflectY: 0, cre: 0, style: "reflect-y" },
            { id: 4, name: "(5, -5)", category: "preStage", moveType: "translate", ixt: 5, iyt: -5, style: "translate" },
            { id: 5, name: "180°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: 180, style: "rotate-counter" },
            { id: 6, name: "Reflect Y", category: "preStage", moveType: "reflect", reflectX: 0, reflectY: 1, cre: 0, style: "reflect-x" },
            { id: 7, name: "90°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: -90, style: "rotate-clock" },
            { id: 8, name: "(0, -9)", category: "preStage", moveType: "translate", ixt: 0, iyt: -9, style: "translate" },
            { id: 9, name: "(-5, 3)", category: "preStage", moveType: "translate", ixt: -5, iyt: 3, style: "translate" },
            { id: 10, name: "270°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: -270, style: "rotate-clock" },
            { id: 11, name: "180°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: -180, style: "rotate-clock" },
            { id: 12, name: "90°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: 90, style: "rotate-counter" },
            { id: 13, name: "(0, -1)", category: "preStage", moveType: "translate", ixt: 0, iyt: -1, style: "translate" },
            { id: 14, name: "270°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: 270, style: "rotate-counter" },
        ],
        obstacles: [],
        popUpMessages: ["You Reached the Summit!", "Your Move Supplies Have Run Out!", "You Fell Off the Grid!"],
        theme: {
            backgroundImage: mountainBackground,
            topContainerBackground: "#ffffff44",
            botContainerBackground: "#995e2e44",
            menuContainerBackground: "",
            font: {type: "Courier", color: "#201207"},
            moveColour: {translate: "#006be5", rotate: "#038c8c", reflect: "#69828c", text: "#201207"},
            grid: { axis: 0xC0C0C0, border: 0x000000, text: 0xFFFFFF },
            playerLine: { color: 0xDAA520, weight: 5 },
            playerFill: { color: 0xFFD700, opacity: 1 },
            exitLine: { weight: 6, color: 0x000000 },
            exitFill: { color: 0x000000, opacity: 0.5 },
        },
    },
    {
        level: 3,
        start: [100, 100],
        target: { x1: 10, y1: -6, x2: 10, y2: -9, x3: 6, y3: -9 },
        moves: [
            { id: 1, name: "(2, -8)", category: "preStage", moveType: "translate", ixt: 2, iyt: -8, style: "translate" },
            { id: 2, name: "(3, 4)", category: "preStage", moveType: "translate", ixt: 3, iyt: 4, style: "translate" },
            { id: 3, name: "180°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: 180, style: "rotate-counter" },
            { id: 4, name: "Reflect Y", category: "preStage", moveType: "reflect", reflectX: 0, reflectY: 1, cre: 0, style: "reflect-x" },
            { id: 5, name: "90°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: -90, style: "rotate-clock" },
            { id: 6, name: "(0, -9)", category: "preStage", moveType: "translate", ixt: 0, iyt: -9, style: "translate" },
            { id: 7, name: "(-5, 3)", category: "preStage", moveType: "translate", ixt: -5, iyt: 3, style: "translate" },
            { id: 8, name: "(-3, 0)", category: "preStage", moveType: "translate", ixt: -3, iyt: 0, style: "translate" },
            { id: 9, name: "270°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: -270, style: "rotate-clock" },
            { id: 10, name: "(3, -2)", category: "preStage", moveType: "translate", ixt: 3, iyt: -2, style: "translate" },
            { id: 11, name: "180°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: -180, style: "rotate-clock" },
            { id: 12, name: "90°", category: "preStage", moveType: "rotate", ixro: 0, iyro: 0, rotateFactor: 90, style: "rotate-counter" },
        ],
        obstacles: [],
        popUpMessages: ["You Wrangled Yourself a 'Right Triangle'!", "Yer Outta Moves, Partner!", "That There's Outta Bounds!"],
        theme: {
            backgroundImage: desertBackground,
            topContainerBackground: "#ffffff44",
            botContainerBackground: "#995e2e44",
            menuContainerBackground: "",
            font: {type: "Courier", color: "#201207"},
            moveColour: {translate: "#e28822", rotate: "#e25822", reflect: "#df9f71", text: "#201207"},
            grid: { axis: 0xFF0000, border: 0x000000, text: 0x000000 },
            playerLine: { color: 0xDAA520, weight: 5 },
            playerFill: { color: 0xFFD700, opacity: 1 },
            exitLine: { weight: 6, color: 0x000000 },
            exitFill: { color: 0x000000, opacity: 0.5 },
        },
    },
]

export default levels